import { Package, Provider, ShopProduct } from "./types";

export const providers: Provider[] = [
  {
    id: "vumatel",
    name: "Vumatel",
    logo: "/providers/vumatel.png",
    rating: 4.5,
    sla: "99.5%",
  },
  {
    id: "openserve",
    name: "Openserve",
    logo: "/providers/openserve.png",
    rating: 4.2,
    sla: "99.3%",
  },
  {
    id: "frogfoot",
    name: "Frogfoot",
    logo: "/providers/frogfoot.png",
    rating: 4.1,
    sla: "99.2%",
  },
  {
    id: "linklayer",
    name: "Linklayer",
    logo: "/providers/linklayer.png",
    rating: 4.0,
    sla: "99.0%",
  },
];

export const packages: Package[] = [
  {
    id: "vuma-50-50",
    providerId: "vumatel",
    name: "Vumatel 50/50Mbps",
    speedDown: 50,
    speedUp: 50,
    price: 699,
    features: ["Free Router", "Free Installation"],
    contractTerm: "Month-to-month",
    hasRouter: true,
    hasInstallation: true,
    uncapped: true,
    type: "fibre"
  },
  {
    id: "vuma-100-100",
    providerId: "vumatel",
    name: "Vumatel 100/100Mbps",
    speedDown: 100,
    speedUp: 100,
    price: 899,
    features: ["Free Router", "Free Installation"],
    contractTerm: "Month-to-month",
    hasRouter: true,
    hasInstallation: true,
    uncapped: true,
    type: "fibre"
  },
  {
    id: "openserve-50-25",
    providerId: "openserve",
    name: "Openserve 50/25Mbps",
    speedDown: 50,
    speedUp: 25,
    price: 649,
    features: ["Free Router", "Free Installation"],
    contractTerm: "Month-to-month",
    hasRouter: true,
    hasInstallation: true,
    uncapped: true,
    type: "fibre"
  },
  {
    id: "openserve-100-50",
    providerId: "openserve",
    name: "Openserve 100/50Mbps",
    speedDown: 100,
    speedUp: 50,
    price: 849,
    features: ["Free Router", "Free Installation"],
    contractTerm: "Month-to-month",
    hasRouter: true,
    hasInstallation: true,
    uncapped: true,
    type: "fibre"
  },
];

export const webhostingPackages: Package[] = [
  {
    id: "wh-starter",
    providerId: "quantum-host",
    name: "Starter Host",
    speedDown: 0,
    speedUp: 0,
    price: 99,
    features: ["10GB SSD Storage", "10 Email Accounts", "1 Website"],
    contractTerm: "Monthly",
    hasRouter: false,
    hasInstallation: false,
    uncapped: false,
  },
  {
    id: "wh-business",
    providerId: "quantum-host",
    name: "Business Host",
    speedDown: 0,
    speedUp: 0,
    price: 199,
    features: ["50GB SSD Storage", "50 Email Accounts", "5 Websites"],
    contractTerm: "Monthly",
    hasRouter: false,
    hasInstallation: false,
    uncapped: false,
  },
  {
    id: "wh-pro",
    providerId: "quantum-host",
    name: "Pro Host",
    speedDown: 0,
    speedUp: 0,
    price: 299,
    features: ["100GB SSD Storage", "Unlimited Email Accounts", "Unlimited Websites"],
    contractTerm: "Monthly",
    hasRouter: false,
    hasInstallation: false,
    uncapped: false,
  },
];

export const voipPackages: Package[] = [
  {
    id: "voip-basic",
    providerId: "quantum-voip",
    name: "VoIP Basic",
    speedDown: 0,
    speedUp: 0,
    price: 149,
    features: ["Per-second billing", "Keep your number", "Free on-net calls"],
    contractTerm: "Monthly",
    hasRouter: false,
    hasInstallation: false,
    uncapped: false,
  },
  {
    id: "voip-business",
    providerId: "quantum-voip",
    name: "VoIP Business",
    speedDown: 0,
    speedUp: 0,
    price: 249,
    features: ["All Basic features", "Voicemail to email", "Call forwarding"],
    contractTerm: "Monthly",
    hasRouter: false,
    hasInstallation: false,
    uncapped: false,
  },
  {
    id: "voip-enterprise",
    providerId: "quantum-voip",
    name: "VoIP Enterprise",
    speedDown: 0,
    speedUp: 0,
    price: 499,
    features: ["All Business features", "Auto-attendant (IVR)", "Call recording"],
    contractTerm: "Monthly",
    hasRouter: false,
    hasInstallation: false,
    uncapped: false,
  },
];

export const shopProducts: ShopProduct[] = [
  {
    id: 'inverter-5kw',
    name: '5kW Inverter with 5.12kWh Battery',
    price: 35999,
    currency: 'ZAR',
    image: '/shop/inverter-1.jpg',
    description: 'A powerful inverter and battery combination to keep your home running during outages. Ideal for essential loads.',
    category: 'Inverters',
    specs: [
      '5kW Pure Sine Wave Inverter',
      '5.12kWh LiFePO4 Battery',
      '6000+ Cycle Life',
      'Smart Battery Management System',
    ],
    features: [
      'Automatic switchover',
      'Solar ready',
      'Compact design',
      '5-year warranty on battery',
    ],
    whatsIncluded: ['5kW Inverter', '5.12kWh Battery', 'Wall-mount bracket', 'Communication cables'],
  },
  {
    id: 'router-wifi6',
    name: 'AX3000 Wi-Fi 6 Router',
    price: 1299,
    currency: 'ZAR',
    image: '/shop/router-1.jpg',
    description: 'Experience next-generation Wi-Fi with faster speeds, greater capacity, and reduced latency.',
    category: 'Networking',
    specs: [
      'Dual-Band Wi-Fi 6 (802.11ax)',
      'Speeds up to 3000Mbps',
      '4x Gigabit Ethernet Ports',
      'OFDMA and MU-MIMO technology',
    ],
    features: [
      'WPA3 Security',
      'Easy setup via app',
      'Beamforming technology',
      'Parental Controls',
    ],
    whatsIncluded: ['AX3000 Router', 'Power Adapter', 'Ethernet Cable', 'Quick Start Guide'],
  },
];
